Fall-2021-UIA/itk201_project/UNIMEET/UNIMEET/Models/ApplicationUser.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using Microsoft.AspNetCore.Identity;
using UNIMEET.Models;


namespace UNIMEET.Data
{
    public class ApplicationUser : IdentityUser
    {   
        [Required]
        public string Nickname { get; set; }
        public string CalenderFile { get; set; }
        
        public string Firstname { get; set; }
        
        public string Lastname { get; set; }
        
        public string About { get; set; }
        
        // Making one to many relationships
        public ICollection<CalendarUrl> CalendarUrls { get; set; } = new List<CalendarUrl>();



        // Making a many to many relationship between users and groups
        public ICollection<Group> Groups { get; set; } = new List<Group>();
        
        
        
        // Creating many to many relationships toward itself for contacts
        public ICollection<ApplicationUser> Contacts { get; set; } = new List<ApplicationUser>();
        public ICollection<ApplicationUser> OtherUser { get; set; } = new List<ApplicationUser>();
        
        // Creating many to many relationships toward itself for contact requests
        public ICollection<ApplicationUser> ContactRequestSender { get; set; } = new List<ApplicationUser>();
        public ICollection<ApplicationUser> ContactRequestReceiver { get; set; } = new List<ApplicationUser>();

  

    }
}

Fall-2021-UIA/itk201_project/UNIMEET/UNIMEET/Controllers/ApplicationUserController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using UNIMEET.Data;
using UNIMEET.Models;

namespace UNIMEET.Controllers
{
    public class ApplicationUserController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _um;
        
        public ApplicationUserController(ApplicationDbContext context, UserManager<ApplicationUser> um)
        {
            _context = context;
            _um = um;
        }

        // GET: ApplicationUser/Details/5
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser.
                Include(applicationUser => applicationUser.Groups).
                Include(applicationUser => applicationUser.Contacts).
                Include(applicationUser => applicationUser.OtherUser).
                Include(applicationUser => applicationUser.ContactRequestReceiver).
                Include(applicationUser => applicationUser.ContactRequestSender).
                FirstOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            ViewBag.currentUser = _um.Users.
                Where(a => a.Id == _um.GetUserId(User)).
                Include(a => a.Contacts).
                Include(a => a.ContactRequestReceiver).
                Include(a => a.ContactRequestSender).
                FirstOrDefaultAsync().Result;

            return View(applicationUser);
        }

        // Helper function for sidebar preview. 
        [HttpGet]
        public async Task<IActionResult> SidebarPreview()
        {
            var user = await _um.GetUserAsync(User);
            // User is not signed in.
            if (user == null)
            {
                return NoContent();
            }

            string url = Request.Headers["Referer"].ToString();
            
            // User is in account setting. 
            if (url.Contains("Account"))
            {
                return NoContent();
            }
            
            return PartialView("_SideBarPartial");
        }
        
        
        /* This function gets the authorized users contacts.*/
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Friends()
        {
            // UserId authorized.
            var id = _um.GetUserId(User);
            // Need to get the user authorized with their contacts. 
            var applicationUser = await _context.ApplicationUser.
                Include(applicationUser => applicationUser.Contacts).
                Include(u => u.ContactRequestSender).
                FirstOrDefaultAsync(m => m.Id == id);
            
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }
        
        /* This function gets the authorized users contact requests and returns a partial view. */
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> FriendRequests()
        {
            // UserId authorized.
            var id = _um.GetUserId(User);
            // Need to get the user authorized with their contact requests. 
            var applicationUser = await _context.ApplicationUser.
                Include(applicationUser => applicationUser.ContactRequestSender).
                FirstOrDefaultAsync(m => m.Id == id);
            
            if (applicationUser == null)
            {
                return NotFound();
            }

            return PartialView("_FriendRequestPartial" ,applicationUser);
        }
        
        

        // Function for searching after user
        [HttpGet]
        [Authorize]

        public async Task<IActionResult> SearchApplicationUser(string searchString)
        { 
            // Convert search string to lower case, if the string is not empty
            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
            }
            //Contacts needs to be in included inorder to check if the user already has the current user as a contact
             //ContactRequestReceiver needs to be added inorder to check if the current user has sent a contact request to the user
             //ContactRequestSender need to be added inorder to check if the user has sent a contact request to the current user
             var result = _context.ApplicationUser.
                Include(m => m.Contacts).
                Include(m => m.ContactRequestReceiver).
                Include(m => m.ContactRequestSender).
                Where(m => m.Nickname.ToLower().Contains(searchString) || m.Email.ToLower().Contains(searchString)).
                Where(m => m.Id != _um.GetUserId(User)).
                OrderBy(m => m.Email).
                Take(10); // Only taking 10 results to prevent a huge response in the view
            
            
            var currentApplicationUser = await _context.ApplicationUser.
                FirstOrDefaultAsync(m => m.Id == _um.GetUserId(User));
            
            // Storing the current user in ViewData so that it can be accessed in the view to check for contacts and contact requests
            ViewData["CurrentApplicationUser"] = currentApplicationUser;

            return PartialView("_UsersPartial", result.ToList());
        }
        
        // Function for returning the partial view of the search for users view
        [HttpGet]
        [Authorize]
        public IActionResult SearchForContactPartial()
        {
            return PartialView("_SearchForNewContactPartial");
        }
        
        // Function for returning the partial view of the outgoing contact requests
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> OutgoingContactRequestsPartial()
        {
            // UserId authorized.
            var id = _um.GetUserId(User);
            
            if (id == null)
            {
                return NotFound(); 
            }
            
            // Need to get the user authorized with their contact requests. 
            var applicationUser = await _context.ApplicationUser.
                Include(applicationUser => applicationUser.ContactRequestReceiver).
                FirstOrDefaultAsync(m => m.Id == id);

            return PartialView("_ContactsOutgoingPartial", applicationUser);
        }
        
        // Function for returning partial view for incoming contact requests
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> IncomingContactRequestPartial()
        {
            var id = _um.GetUserId(User);
            var applicationUser = await _context.ApplicationUser
                .Include(applicationUser => applicationUser.ContactRequestSender).
                FirstOrDefaultAsync(m => m.Id == id);

            return PartialView("_incomingContactRequest", applicationUser);
        }

        // Function for returning the partial view of the groups the current user has in common with userId
        [Route("ApplicationUser/CommonGroups/{userId}")]
        public async Task<IActionResult> CommonGroups(string userId)
        {
            var currentUser = await _um.GetUserAsync(User);
            
            if (currentUser == null)
            {
                return NotFound(); 
            }

            var otherUser = _um.Users.FirstOrDefault(u => u.Id == userId);
            
            if (otherUser == null)
            {
                return NotFound(); 
            }
            
            // Get the groups the userID has, and the groups the current user has in common
            var commonGroups = _context.Groups
                .Include(g => g.ApplicationUsers)
                .Where(g => g.ApplicationUsers.Contains(otherUser) && g.ApplicationUsers.Contains(currentUser))
                .OrderBy(g => g.Name)
                .Take(40);
            

            return PartialView("_commonGroupsPartial", commonGroups);
        }
        
        
        // Function for searching and display contacts the current user has accepted
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> SearchApplicationContact(string searchString)
        {
            // Convert search string to lower case, if the string is not empty
            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
            }
            //Contacts needs to be in included inorder to check if the user already has the current user as a contact
            var result = _um.Users.
                Include(m => m.Contacts).
                Where(m => m.Nickname.ToLower().Contains(searchString) || m.Email.ToLower().Contains(searchString)).
                Where(m => m.Id != _um.GetUserId(User)).
                OrderBy(m => m.Email).
                Take(10); 
            
            var currentApplicationUser = await _context.ApplicationUser.
                FirstOrDefaultAsync(m => m.Id == _um.GetUserId(User));
            
            // Storing the current user in ViewData so that it can be accessed in the view to check for contacts and contact requests
            ViewData["CurrentApplicationUser"] = currentApplicationUser;

            return PartialView("_CreateGroupUserPartial", result.ToList());
        }

        // Functions for adding sending a contact request 
        [HttpPost]
        [Authorize]

Fall-2021-UIA/itk201_project/UNIMEET/UNIMEET/Views/ApplicationUser/Details.cshtml
@model UNIMEET.Data.ApplicationUser
@using System.Linq;
@using System.Text.RegularExpressions
@using Microsoft.CodeAnalysis.CSharp.Syntax
@using UNIMEET.Data

@* Hidden input for user id *@
<div id="user-id" type="hidden" value="@Model.Id"></div>

<div class="container">
	<div class="row gutters">
		<div class="col-xl-3 col-lg-3 col-md-11 col-sm-11 col-11">
			<div class="card h-100">
				<div class="card-body">
					<div class="account-settings">
						<div class="user-profile">
							@{
								Regex rgx = new Regex("[^a-zA-Z0-9-]");
								var safeName = rgx.Replace(Model.Nickname, "");
								var imagePath = @"https://avatars.dicebear.com/api/initials/" + @safeName + ".svg";
								
								<div class="user-avatar">
									<img class="rounded-circle" alt="@Model.Nickname" src="@imagePath" width="50" height="50">
								</div>
								<h5 class="user-name">@Html.DisplayFor(model => model.Firstname) @Html.DisplayFor(model => model.Lastname)</h5>
								<h6 class="user-name">@Html.DisplayFor(model => model.Nickname)</h6>
								<h6 class="user-email">@Html.DisplayFor(model => model.Email)</h6>
							}
							
						</div>
						<div class="about">
							<h6 class="about mb-2">About</h6>
							<p>@Html.DisplayFor(model => model.About)</p>
							<hr/>
							<div class="form-group">
								@if (((ApplicationUser) ViewBag.currentUser).Contacts.Contains(Model))
								{
									<form asp-action="RemoveContact">
										<input asp-for="Id" type="hidden" value="@Model.Id"/>
										<input type="submit" value="Remove contact" class="btn btn-primary"/>
									</form>
								}
								else if (((ApplicationUser) ViewBag.currentUser).ContactRequestSender.Contains(Model))
								{
									<form asp-action="AcceptContactRequest">
										<input asp-for="Id" type="hidden" value="@Model.Id"/>
										<input type="submit" value="Accept request" class="btn btn-primary"/>
									</form>
									<br/>
									<form asp-action="RemoveContactRequest">
										<input asp-for="Id" type="hidden" value="@Model.Id"/>
										<input type="submit" value="Decline request" class="btn btn-primary"/>
									</form>
								}
								else if (((ApplicationUser) ViewBag.currentUser).ContactRequestReceiver.Contains(Model))
								{
									<p>You have sent a contact request to this user</p>
								}
								else if (((ApplicationUser) ViewBag.currentUser).Id == Model.Id)
								{
									
								}
								else
								{
									<form asp-action="NewContactRequest">
										<input asp-for="Id" type="hidden" value="@Model.Id"/>
										<input type="submit" value="Send contact request" class="btn btn-primary"/>
									</form>
								}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-xl-9 col-lg-9 col-md-11 col-sm-11 col-11">
			<div class="card h-100">
				<div class="group-settings">
					<h6 class="group">Common Groups</h6>
				</div>
				<div class="card-body">
					<div class="row gutters">
						<div id="common-groups" class="col-xl-11 col-lg-11 col-md-11 col-sm-11 col-11">
							@* Users common groups will appear here *@
							
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script src="~/js/commonGroups.js"></script>

Fall-2021-UIA/itk201_project/UNIMEET/UNIMEET/Views/ApplicationUser/Friends.cshtml
@using System.Text.RegularExpressions
@model UNIMEET.Data.ApplicationUser


<div class="container-fluid">
    <div class="row">
        <div class="col-sm-11 col-md-11 col-lg-11">
            @* This needs to be the main view *@
            <div class="row">
                <div class="col-sm-5 col-md-5 col-lg-5">
                    @* Incoming contact requests *@
                    <a class="changeCursor" onclick="contactsIncomingPartial()">
                        <img class="rounded-circle" alt="Incoming contact requests" src="~/assets/img/incoming-call-svgrepo-com.svg" width="25" height="25">
                        Incoming contact requests
                    </a>
                </div>
                <div class="col-sm-5 col-md-5 col-lg-5">
                    @* Outgoing contact requests *@
                    <a class="changeCursor" onclick="contactsOutgoingPartial()">
                        <img class="rounded-circle" alt="Outgoing contact requests" src="~/assets/img/outgoing-call-svgrepo-com.svg" width="25" height="25">
                        Outgoing contact requests
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12">
                    <div id="contacts-main-view">
                        @* Dynamic div updated based on page content *@
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1">
            @* This needs to be to the right *@
            <table class="table noBorder">
                <tbody class="noBorder">
                <tr class="noBorder">
                    <td class="noBorder">
                        <div class="text-light">
                            Nickname
                        </div>
                    </td>
                </tr>
                @foreach (var contact in Model.Contacts)
                {
                    Regex rgx = new Regex("[^a-zA-Z0-9-]");
                    var safeName = rgx.Replace(@contact.Nickname, "");
                    var imagePath = @"https://avatars.dicebear.com/api/initials/" + @safeName + ".svg";
                    <tr class="noBorder">
                        <td class="noBorder">
                            <a class="nav-link text-light" asp-controller="ApplicationUser" asp-action="Details" asp-route-id="@contact.Id">
                                <span class="hovertext-left" data-hover="@contact.Nickname">
                                    <img class="rounded-circle" alt="@contact.Nickname" src="@imagePath" width="50" height="50">
                                </span>
                            </a>
                        </td>
                    </tr>
                }

                <div id="add-member-to-group">
                    <tr class="noBorder">
                        <td class="noBorder">
                            @* This should update the add user by email view *@
                            <span class="hovertext-left" data-hover="Add a new contact">
                                <img class="rounded-circle" onclick="searchForUserPartial()" alt="Add a new contact" src="~/assets/img/add-filled-svgrepo-com.svg" width="50" height="50">
                            </span>
                        </td>
                    </tr>
                </div>
                </tbody>
            </table>
        </div>
    </div>
</div>