Fall-2021-UIA/ikt201/assignment_3/Models/ErrorViewModel.cs
using System;

namespace assignment_3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Fall-2021-UIA/ikt201/assignment_3/Models/GuestModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace assignment_3.Models
{
    public class GuestModel
    {
        public GuestModel() {}

        public GuestModel(string name,string title,string message)
        {
            Name = name;
            Title = title;
            Message = message;
        }
        
        public int Id { get; set; }
        
        [Required(ErrorMessage = "Name is required")]
        [StringLength(20, MinimumLength = 1)]
        [DisplayName("Name")]
        public string Name { get; set; }
        
        
        

        [Required(ErrorMessage = "Title is required")]
        [MinLength(5, ErrorMessage = "Must be at least 5 chars"),MaxLength(50)]
        [DisplayName("Title")]
        public string Title { get; set; }
        
        

        [Required(ErrorMessage = "Message is required")]
        [MinLength(20, ErrorMessage = "Must be at least 20 chars"),MaxLength(200)]
        [DisplayName("Message")]
        public string Message { get; set; }
        
        
        
    }
}

Fall-2021-UIA/ikt201/assignment_3/Controllers/GuestbookController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Threading.Tasks;
using assignment_3.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using assignment_3.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;


namespace assignment_3.Controllers
{
    public class GuestbookController : Controller
    {
        
        private readonly ILogger<GuestbookController> _logger;
        private readonly ApplicationDbContext _db;

        public GuestbookController(ILogger<GuestbookController> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }

    

        public async Task<IActionResult> Index()
        {
            return View(await _db.Guests.ToListAsync());
        }
        
        
        [HttpPost]
        public IActionResult Add(GuestModel guest)
        {

            if(ModelState.IsValid){
                _db.Guests.Add(guest);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            

            return View(guest);
            
        }
        
        [HttpGet]
        public IActionResult Add()
        {
            GuestModel guest = new GuestModel();
            return View(guest);
        }
            

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
        
    }
}

Fall-2021-UIA/ikt201/assignment_3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using assignment_3.Models;

namespace assignment_3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

Fall-2021-UIA/ikt201/assignment_3/Views/Guestbook/Add.cshtml
@model GuestModel
@{
    ViewData["Title"] = "New entry page";
}



<form method="post">
    <ul>
        <li>
            <label asp-for="Name"></label>
            <input asp-for="Name">
        </li>
        <li>
        <label asp-for="Title"></label>
        <input asp-for="Title">
        </li>

        <li>
        <label asp-for="Message"></label>
        <textarea asp-for="Message"></textarea>
        </li>
    </ul>
    <input type="submit" id="Submit">
    
</form>

Fall-2021-UIA/ikt201/assignment_3/Views/Guestbook/Index.cshtml
@model IEnumerable<assignment_3.Models.GuestModel>



<a id="Add" asp-area="" asp-controller="Guestbook" asp-action="Add">Add</a>
<h1 class="special-border">All entries</h1>


@foreach (var item in Model)
{
    <div class="entry-box">
        <h3>Name: @item.Name</h3>
        <h3>Title: @item.Title</h3>
        <p>@item.Message)</p>
    </div>
}

Fall-2021-UIA/ikt201/assignment_3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Fall-2021-UIA/ikt201/assignment_3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - assignment_3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/mycss.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Guestbook" asp-action="Index">Entries</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Guestbook" asp-action="Add">Create new entrie</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - assignment_3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>