Fall-2021-UIA/itk201_project/UNIMEET/UNIMEET/Models/Group.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using UNIMEET.Data;

namespace UNIMEET.Models
{
    public class Group
    {
        
        public Group() {}

        public Group(string name)
        {
            Name = name;
        }
        
        public int Id { get; set; }
        
        [Required]
        [StringLength(20,MinimumLength = 3)]
        public string Name { get; set; }
        
        
        // Many to many between Groups and ApplicationUsers
        public ICollection<ApplicationUser> ApplicationUsers { get; set; } = new List<ApplicationUser>();
        
        // Making many to one relation so that groups can have events
        public ICollection<Event> Events { get; set; } = new List<Event>();
        
    }
}

Fall-2021-UIA/itk201_project/UNIMEET/UNIMEET/Controllers/GroupController.cs
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using UNIMEET.Data;
using UNIMEET.Models;

namespace UNIMEET.Controllers
{
    [Authorize]
    public class GroupController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _um;

        public GroupController(ApplicationDbContext context, UserManager<ApplicationUser> um)
        {
            _context = context;
            _um = um;
        }


        [HttpPost]
        [Route("Group/AddUsersToGroup/{groupId:}")]
        public async Task<IActionResult> AddUsersToGroup(string groupId)
        {
            var group = await _context.Groups.FirstOrDefaultAsync(g => g.Id == Convert.ToInt32(groupId));
            var userIds = JsonConvert.DeserializeObject<List<string>>(Request.Form["selected"]);
            foreach (var id in userIds)
            {
                var user = await _um.Users.FirstOrDefaultAsync(u => u.Id == id);
                if (user == null)
                {
                    return NotFound();
                }
                group.ApplicationUsers.Add(user);
            }

            await _context.SaveChangesAsync();
            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> RemoveUserFromGroup(string userId, string groupId)
        {
            var applicationUser = await _context.ApplicationUser.FindAsync(userId);
            if (applicationUser == null)
            {
                return NotFound();
            }
            
            var group = await _context.Groups.FindAsync(groupId);
            if (group == null)
            {
                return NotFound();
            }

            if (group.ApplicationUsers.Contains(applicationUser))
            {
                group.ApplicationUsers.Remove(applicationUser);
                await _context.SaveChangesAsync();
                return Ok();
            }
            else
                return NotFound();
        }
        
        
        [Route("Group/GroupMembers/{groupId}")]
        public async Task<IActionResult> GroupMembers(string groupId)
        {
            var group = await _context.Groups
                .Include(g => g.ApplicationUsers)
                .ThenInclude(u => u.Contacts)
                .FirstOrDefaultAsync(g => g.Id == Convert.ToInt32(groupId));
            if (group == null)
            {
                return NotFound(); 
            }
            
            // Save the current user ID to the view bag
            ViewBag.CurrentUser = await _um.GetUserAsync(User);

            return PartialView("_GroupMembersPartial", group);
        }

        // GET: Groups
        /*
         * This function returns a partial view that consist of html code for the groups.
        */
        [HttpGet]
        public IActionResult Index()
        {
            // Query to get the user currently logged in.
            var user =_um.Users
                .Include(u => u.Groups) // Including Groups, because this is not default.
                .FirstOrDefault(u => u.Id == _um.GetUserId(User)); 
            if (user == null)
            {
                return NotFound();
            }

            return PartialView("_GroupPartial", user.Groups.ToList());
        }

        // GET: Group/Details/5
        // Returns details of the group.
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            /* Nested looping is slow. So lazy loading is turned on by default. That means we cant access ApplicationUsers by default
             Include lets you access ApplicationUsers, thus you can use it in the html */
            var group = await _context.Groups.Include(group => group.ApplicationUsers)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (group == null)
            {
                return NotFound();
            }
            
            return View(group);
        }
        

        // GET: Group/Create
        // Returns a view for creating a group.
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Group/Create
        [HttpPost]
        public async Task<IActionResult> CreateGroupWithMembers()
        {
            // Creating a new group (Group entity).
            var group = new Group
            {
                Name = Request.Form["name"]
            };
            
            _context.Groups.Add(group);
            await _context.SaveChangesAsync();
            // Converting json serialized javaScript array of strings to c# list of strings.
            var userIds = JsonConvert.DeserializeObject<List<string>>(Request.Form["selected"]);

            // Iterating over user ids.
            foreach (var id in userIds)
            {
                // Query for user.
                var user = await _um.Users.FirstOrDefaultAsync(u => u.Id == id);
                // Return not found if a user doesnt exist. No users will be saved.
                if (user == null)
                {
                    return NotFound();
                }
                // Adding user to group.
                group.ApplicationUsers.Add(user);
            }
            // Adding user that created the group.
            var creator = await _um.GetUserAsync(User);
            if (creator == null)
            {
                return NotFound();
            }
            group.ApplicationUsers.Add(creator);

            // Storing in database.
            await _context.SaveChangesAsync();
            
            // Redirecting user to Group/Details/groupId view.
            return RedirectToAction("Details", new { id = group.Id });
        }
        
    
        
        // GET: Group/Edit/
        // Returns a view with an edit form for the user to fill inn.
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            // Finds the group using context and id send in.
            var @group = await _context.Groups.FindAsync(id);
            if (@group == null)
            {
                return NotFound();
            }
            return View(@group);
        }

        // POST: Group/Edit/5
        // Store the edited group data in the database.
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Group @group)
        {
            if (id != @group.Id)
            {
                return NotFound();
            }
            // Checks if the form is send in is valid.
            if (ModelState.IsValid)
            {
                try
                {
                    // Updating the group with new parameter etc.
                    _context.Update(@group);
                    await _context.SaveChangesAsync();
                }
                // Error handler.
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(@group.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                // Redirect the user to the homepage.
                return RedirectToAction(nameof(Details), new { id = @group.Id });
            }
            return View(@group);
        }
        
        [HttpPost]
        [Route("Group/SearchGroupContacts/{groupId:}/{searchString:}")]
        public async Task<IActionResult> SearchGroupContacts(string groupId, string searchString)
        {
            var id = _um.GetUserId(User);
            if (id == null)
            {
                return NotFound();
            }
            
            var group = await _context.Groups
                .Include(g => g.ApplicationUsers)
                .FirstOrDefaultAsync(g => g.Id == Convert.ToInt32(groupId));
            
            if (group == null)
            {
                return NotFound();
            }

            var user = await _um.Users
                .Include(u => u.Contacts)
                .FirstOrDefaultAsync(u => u.Id == id);

            if (user == null)
            {
                return NotFound();
            }


            var users = user.Contacts
                .Where(u => !group.ApplicationUsers.Contains(u))
                .Where(u => u.Nickname.ToLower().Contains(searchString.ToLower()) | u.Email.ToLower().Contains(searchString.ToLower()))
                .OrderBy(u => u.Nickname)
                .Take(5);
            if (!users.Any())
            {
                return NotFound();
            }

            ViewBag.selected = Request.Form["selected"];
            return PartialView("_SearchGroupContactsPartial", users);
        }

        // POST: Group/Leave/5
        // Function for removing user from a group.
        [HttpPost]
        [Route("Group/LeaveGroup/{id:}")]
        public async Task<IActionResult> LeaveGroup(string id)
        {
            if (!int.TryParse(id, out var groupId))
            {
                return NotFound();
            }
            // Finds the group.
            var @group = await _context.Groups
                .Include(g => g.ApplicationUsers)
                .FirstOrDefaultAsync(g => g.Id == groupId);

            if (@group == null)
            {
                return NoContent();
            }
            
            // Logged in user

Fall-2021-UIA/itk201_project/UNIMEET/UNIMEET/Views/Group/Create.cshtml
@model UNIMEET.Models.Group

@{
    ViewData["Title"] = "Create";
}

<h1>Create new group</h1>

<div class="row">
    <div class="col-md-8">
        <div class="row">
                <div class="col-md">
                    <input id="group_name" class="form-control fieldLength" placeholder="Group name"/>
                </div>
                <div class="col-md">
                    <input value="Create your group" onclick="create_group_with_members()" spellcheck="false" class="btn btn-primary float-left"/>
                </div>
            </div>
        <br />
        <div class="row">
            <div class="col-md">
                <input id="searchbarContacts" class="form-control fieldLength" placeholder="Contact search" onkeyup="searchFriend()"/>
                <div id="contactsResult" class="fieldLength"></div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <p>Chosen contacts are displayed here</p>
        <ul id="selectedList" style="list-style-type: none"></ul>
    </div>
</div>

Fall-2021-UIA/itk201_project/UNIMEET/UNIMEET/Views/Group/Details.cshtml
@model UNIMEET.Models.Group

@{
    ViewData["Title"] = "Details";
}

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-sm-11 col-md-11 col-lg-11">
                @* This needs to be the main view *@
                <div class="noBorder">
                    <h2>@Model.Name</h2> 
                    <a class="btn btn-primary changeCursor" asp-controller="Group" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                    <a class="btn btn-danger changeCursor" onclick="LeaveGroup()">Leave</a>
                </div>
                <div id="event-showcase"></div>
                <div id="timeSlotsCalendar" > </div>
                <div class="calendar-event-placement-container">
                    <div id="calendarEventSuccessfullyCreated"></div>
                </div>
                

                <input id="submitCalenderEvent" type="hidden" value="Submit" onclick="submitCalenderEvent()"/>
                <div id="add-user-to-group-view">
                    <div style="visibility: hidden" id="group-member-search-div">
                        Search for a contact to add as group member:
                        <input id="group-member-search-string" type="search" onkeyup="searchNewGroupMembers()"/>
                    </div>
                    <div id="new-group-members"></div>
                    <br/>
                    <button class="btn btn-primary" id="add-contact-to-group" onclick="AddContactsToGroup()" style="visibility: hidden">Add</button>

                    <div id="group-id" type="hidden" value="@Model.Id"></div>

                    <div style="visibility: hidden">
                        <ul id="selected-id">

                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-sm-1 col-md-1 col-lg-1">
                @* This needs to be to the right *@
                <table class="table noBorder">
                    <tbody>
                    <div id="group-members"></div>
                    
                    <div id="add-member-to-group">
                        <tr class="noBorder">
                            <td class="noBorder">
                            <span class="hovertext-left" data-hover="Toggle add group member">
                                <img class="rounded-circle changeCursor" onclick="displayContactSearch()" alt="Toggle add group member" src="~/assets/img/add-filled-svgrepo-com.svg" width="50" height="50">
                            </span>
                            </td>
                        </tr>
                    </div>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<script src="~/js/event.js"></script>
<script src="~/js/groupMembers.js"></script>

Fall-2021-UIA/itk201_project/UNIMEET/UNIMEET/Views/Group/Edit.cshtml
@using System.Text.RegularExpressions
@model UNIMEET.Models.Group


@{
    ViewData["Title"] = "Edit";
}
<div id="group-id" type="hidden" value="@Model.Id"></div>
<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-sm-11 col-md-11 col-lg-11">
                @* This needs to be the main view *@
                <div class="row justify-content-center">
                    <div class="noBorder">
                        <h2>@Model.Name</h2>
                    </div>
                </div>
                <br />
                <div class="col-md">
                    <div class="row">
                        @* Displays the group icon *@ 
                        @{
                            Regex rgx = new Regex("[^a-zA-Z0-9-]");
                            var name = rgx.Replace(@Model.Name, "");
                            var imagePath = @"https://avatars.dicebear.com/api/gridy/" + name + ".svg";
                            <tr class="noBorder">
                                <td class="noBorder">
                                    <a class="nav-link text-dark uni-nav-group-list" asp-controller="Group" asp-action="Details" asp-route-id="@Model.Id">
                                        @* TODO: Add hover function for @item.name *@
                                        <span class="hovertext" data-hover="@Model.Name">
                                            <img class="rounded-circle" alt="@Model.Name" src="@imagePath" width="100" height="100">
                                        </span>
                                    </a>
                                </td>
                            </tr>
                        }
                    </div>
                    <br/>
                    <div class="row customPadding">
                        <div class="col-md-4">
                            <form asp-action="Edit">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <input type="hidden" asp-for="Id"/>
                                <div class="form-group">
                                    <label asp-for="Name" class="control-label float-left">Change group name</label>
                                    <input asp-for="Name" class="form-control"/>
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Save changes" class="btn btn-primary"/>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-1 col-md-1 col-lg-1">
                @* This needs to be to the right *@
                <table class="table noBorder">
                    <tbody>
                    <div id="group-members"></div>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<script src="~/js/groupMembers.js"></script>